#- src: git@github.com:kost2191/docker-role.git
- src: https://github.com/kost2191/docker-role.git
  scm: git
  version: master
- src: https://github.com/kost2191/template_file.git
  scm: git
  version: master
